DEFAULT_BACKGROUND = "#15131c"
BLACK_BACKGROUND = "#000000"


MONOSPACE_FONT = "Monospace"


MOBILE_WIDTH = 1080
MOBILE_HEIGHT = 1920
MOBILE_FRAME_WIDTH = 9.0
MOBILE_FRAME_HEIGHT = 16.0


PASTEL_RED = "#ff928a"
PASTEL_ORANGE = "#ffaf80"
PASTEL_GOLD = "#ffcc7a"
PASTEL_YELLOW = "#ffec75"
PASTEL_GREEN = "#8fff8f"
PASTEL_TEAL = "#94ffdf"
PASTEL_BLUE = "#94e4ff"
PASTEL_PURPLE = "#bfc7ff"
PASTEL_VIOLET = "#ddb5ff"
PASTEL_PINK = "#ffadcc"
